Repository game-night-dot-gay/game-night, pull requests merged in 2022-05, with the labels that each got.

#26 Add a package for the frontend code
  flake.nix
  frontend/yarn.lock
Labels: deployment

#28 Add README.md to the project
  README.md
Labels: documentation

#36 Initial CI for the Nix Flake to ensure everything builds
  .github/workflows/nix_ci.yml
Labels: ci

#38 Add initial tracing
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/main.rs
Labels: rust

#49 Infrastructure
  .github/workflows/nix_ci.yml
  .github/workflows/packer.yml
  .github/workflows/terraform.yml
  .gitignore
  flake.nix
  infra/README.md
  infra/images/podman-base/configuration.nix
  infra/images/podman-base/hardware-configuration.nix
  infra/images/podman-prod/configuration.nix
  infra/images/podman-prod/hardware-configuration.nix
  infra/images/podman-prod/nixos.pkr.hcl
  infra/images/podman-prod/plugins.pkr.hcl
  infra/images/podman-prod/variables.pkr.hcl
  infra/terraform/.terraform.lock.hcl
  infra/terraform/firewall.tf
  infra/terraform/main.tf
  infra/terraform/provider.tf
  infra/terraform/variables.tf
  infra/terraform/versions.tf
Labels: deployment

#56 Add design documentation for Authentication
  documentation/design/AUTHENTICATION.md
  documentation/design/USER_MANAGEMENT.md
Labels: design

#65 Switch config to only support toml files
  backend/Cargo.lock
  backend/Cargo.toml
Labels: rust, dependencies

#82 Add Initial Logo
  flake.nix
  frontend/public/img/logo.svg
  frontend/src/assets/logo.png
  frontend/src/views/HomeView.vue
  frontend/yarn.lock
Labels: vuejs

#73 Send emails using SendGrid
  .env
  .github/workflows/nix_ci.yml
  .gitignore
  README.md
  backend/Cargo.lock
  backend/Cargo.toml
  backend/src/api/error.rs
  backend/src/config.rs
  backend/src/email.rs
  backend/src/main.rs
  backend/templates/login.html
  justfile
Labels: rust, dependencies

#99 Allow <object> tags to include files from the same origin
  infra/images/podman-prod/nginx.nix
Labels: bug

#109 Fallback to the / index page when serving the frontend
  backend/src/main.rs
Labels: bug

#110 Document Home Page and Sessions
  documentation/design/API_STRUCTURE.md
  documentation/design/AUTHENTICATION.md
  documentation/design/HOME_PAGE.md
Labels: documentation, design

#115 Add user details
  backend/migrations/20220531134144_add_users_table_details.down.sql
  backend/migrations/20220531134144_add_users_table_details.up.sql
  backend/sqlx-data.json
  backend/src/db/input_sanitization.rs
  backend/src/db/models.rs
  backend/src/db/queries/user.rs
  justfile
Labels: rust
